package com.itus.pojo;
// Generated Dec 4, 2013 3:47:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="bestbuy"
)
public class Account  implements java.io.Serializable {


     private Integer id;
     private Accounttype accounttype;
     private String fullName;
     private String email;
     private String address;
     private String phoneNumber;
     private String company;
     private String username;
     private String password;
     private Boolean isBlock;
     private Boolean isActive;
     private Set comments = new HashSet(0);
     private Set orders = new HashSet(0);

    public Account() {
    }

	
    public Account(Accounttype accounttype) {
        this.accounttype = accounttype;
    }
    public Account(Accounttype accounttype, String fullName, String email, String address, String phoneNumber, String company, String username, String password, Boolean isBlock, Boolean isActive, Set comments, Set orders) {
       this.accounttype = accounttype;
       this.fullName = fullName;
       this.email = email;
       this.address = address;
       this.phoneNumber = phoneNumber;
       this.company = company;
       this.username = username;
       this.password = password;
       this.isBlock = isBlock;
       this.isActive = isActive;
       this.comments = comments;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TypeId", nullable=false)
    public Accounttype getAccounttype() {
        return this.accounttype;
    }
    
    public void setAccounttype(Accounttype accounttype) {
        this.accounttype = accounttype;
    }
    
    @Column(name="FullName", length=50)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    
    @Column(name="Email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="Address", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="PhoneNumber", length=20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    @Column(name="Company", length=100)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    
    @Column(name="Username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="Password", length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="IsBlock")
    public Boolean getIsBlock() {
        return this.isBlock;
    }
    
    public void setIsBlock(Boolean isBlock) {
        this.isBlock = isBlock;
    }
    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="account")
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="account")
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


