package com.bestbuy.pojo;
// Generated Dec 10, 2013 10:12:57 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Accessorydetail generated by hbm2java
 */
@Entity
@Table(name="accessorydetail"
    ,catalog="bestbuy"
)
public class Accessorydetail  implements java.io.Serializable {


     private int id;
     private Product productByAccessoryId;
     private Product productByProductId;

    public Accessorydetail() {
    }

	
    public Accessorydetail(int id) {
        this.id = id;
    }
    public Accessorydetail(int id, Product productByAccessoryId, Product productByProductId) {
       this.id = id;
       this.productByAccessoryId = productByAccessoryId;
       this.productByProductId = productByProductId;
    }
   
     @Id 
    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AccessoryId")
    public Product getProductByAccessoryId() {
        return this.productByAccessoryId;
    }
    
    public void setProductByAccessoryId(Product productByAccessoryId) {
        this.productByAccessoryId = productByAccessoryId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProductId")
    public Product getProductByProductId() {
        return this.productByProductId;
    }
    
    public void setProductByProductId(Product productByProductId) {
        this.productByProductId = productByProductId;
    }




}


