package com.bestbuy.pojo;
// Generated Dec 9, 2013 11:17:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Orderstate generated by hbm2java
 */
@Entity
@Table(name="orderstate"
    ,catalog="bestbuy"
)
public class Orderstate  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Order> orders = new HashSet<Order>(0);

    public Orderstate() {
    }

    public Orderstate(String name, Set<Order> orders) {
       this.name = name;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="Name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="orderstate")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


